DROP DATABASE IF EXISTS adsaworldDB;
CREATE DATABASE adsaworldDB;

USE adsaworldDB;

DROP TABLE IF EXISTS usuarios;
CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);